id: bipenggou_panyang
name: 磐羊湖
location:
  lat: 31.339
  lon: 103.712
  altitude: 3676

capabilities:
  - sunrise
  - sunset
  - cloud_sea
  - autumn_foliage

targets:
  - name: 幺妹峰
    lat: 31.06
    lon: 102.89
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
