id: bipenggou_panyang
name: 磐羊湖
location:
  lat: 31.229248
  lon: 102.870003
  altitude: 3676

capabilities:
  - sunrise
  - sunset
  - cloud_sea
  - autumn_foliage

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
