id: duoraogamu_yala_view
name: 亚拉主景平台
groups:
  - yala
location:
  lat: 30.447693
  lon: 101.540804
  altitude: 4100

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunrise
      - sunset
