id: genie_chachongxi
name: 查冲西村
groups:
  - genie
location:
  lat: 29.742763
  lon: 99.656227
  altitude: 3780

capabilities:
  - sunrise
  - sunset

targets:
  - name: 格聂主峰
    lat: 29.831
    lon: 99.773
    altitude: 6204
    weight: primary
    applicable_events:
      - sunrise
      - sunset
