id: genie_laolenggusi
name: 老冷古寺
groups:
  - genie
location:
  lat: 29.819585
  lon: 99.643822
  altitude: 4100

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 格聂主峰
    lat: 29.831
    lon: 99.773
    altitude: 6204
    weight: primary
    applicable_events:
      - sunrise
      - sunset
