id: genie_eye
name: 格聂之眼
location:
  lat: 29.798288
  lon: 99.759393
  altitude: 4300

capabilities:
  - sunrise
  - sunset
  - stargazing
  - cloud_sea

targets:
  - name: 格聂主峰
    lat: 29.831
    lon: 99.773
    altitude: 6204
    weight: primary
    applicable_events:
      - sunrise
      - sunset
