id: genie_xiazetong
name: 下则通村
location:
  lat: 29.825485
  lon: 99.77077
  altitude: 3890

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 格聂主峰
    lat: 29.831
    lon: 99.773
    altitude: 6204
    weight: primary
    applicable_events:
      - sunrise
      - sunset
