id: genie_nuda_camp
name: 努达营地
groups:
  - genie
location:
  lat: 29.857773
  lon: 99.78883
  altitude: 4480

capabilities:
  - stargazing
  - sunrise

targets:
  - name: 格聂主峰
    lat: 29.831
    lon: 99.773
    altitude: 6204
    weight: primary
    applicable_events:
      - sunrise
