id: gongga_yaha_pass
name: 雅哈垭口
location:
  lat: 29.7425
  lon: 101.723135
  altitude: 4568

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 贡嘎主峰
    lat: 29.596
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events:
      - sunrise
      - sunset
