id: gongga_lenggacuo
name: 冷嘎措
location:
  lat: 29.638151
  lon: 101.69951
  altitude: 4520

capabilities:
  - sunrise
  - sunset
  - stargazing
  - cloud_sea
  - frost

targets:
  - name: 贡嘎主峰
    lat: 29.596
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events:
      - sunrise
      - sunset
