id: gongga_niubei
name: 牛背山（贡嘎）
location:
  lat: 29.77381
  lon: 102.414969
  altitude: 3660

capabilities:
  - sunrise
  - sunset
  - stargazing
  - cloud_sea
  - snow_tree

targets:
  - name: 贡嘎主峰
    lat: 29.596
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events:
      - sunrise
      - sunset
