id: lianbaoyeze_zhagaer
name: 扎尕尔措
groups:
  - other
location:
  lat: 33.066421
  lon: 101.174174
  altitude: 4200

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 莲宝叶则主峰
    lat: 33.004
    lon: 100.742
    altitude: 5141
    weight: primary
    applicable_events:
      - sunrise
      - sunset
