id: majiagou_main_view
name: 主沟观景点
groups:
  - other
location:
  lat: 29.643257
  lon: 102.125221
  altitude: 3320

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
