id: siguniang_haizi_chaoshanping
name: 海子沟-朝山坪
groups:
  - siguniang
location:
  lat: 30.996446
  lon: 102.838233
  altitude: 3820

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
