id: siguniang_shuangqiao
name: 双桥沟
groups:
  - siguniang
location:
  lat: 30.982511
  lon: 102.768042
  altitude: 3250

capabilities:
  - sunrise
  - sunset
  - cloud_sea
  - frost

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
