id: siguniang_changping
name: 长坪沟
groups:
  - siguniang
location:
  lat: 31.014731
  lon: 102.857694
  altitude: 3400

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
