id: tagong_muya
name: 木雅金塔机位
groups:
  - other
location:
  lat: 30.323371
  lon: 101.526473
  altitude: 3730

capabilities:
  - sunset
  - stargazing

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunset
