id: transit_lixiao_redstone
name: 理小路红石滩（凉台沟）
groups:
  - lixiao
location:
  lat: 31.388087
  lon: 102.876353
  altitude: 3490

capabilities:
  - sunset

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunset
