id: transit_jianziwan_pass
name: 剪子弯山垭口
groups:
  - 318
location:
  lat: 30.021268
  lon: 100.796678
  altitude: 4659

capabilities:
  - sunrise
  - sunset

targets:
  - name: 海子山主峰
    lat: 29.95
    lon: 100.35
    altitude: 5020
    weight: primary
    applicable_events:
      - sunrise
      - sunset
