id: transit_lixiao_tunnel_view
name: 理小隧道口观景台
groups:
  - lixiao
location:
  lat: 31.310194
  lon: 102.744718
  altitude: 3900

capabilities:
  - sunrise
  - sunset

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunrise
      - sunset
