id: transit_xinduqiao_view
name: 新都桥镇外机位
location:
  lat: 30.03
  lon: 101.509
  altitude: 3400

capabilities:
  - sunrise
  - sunset

targets:
  - name: 贡嘎主峰
    lat: 29.58
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events:
      - sunrise
      - sunset
