id: transit_daerpu_valley
name: 大二普
location:
  lat: 31.38526
  lon: 102.991165
  altitude: 3300

capabilities:
  - sunset
  - stargazing

targets:
  - name: 幺妹峰
    lat: 31.106
    lon: 102.902
    altitude: 6247
    weight: primary
    applicable_events:
      - sunset
