id: transit_gaoersi_pass
name: 高尔寺山垭口
location:
  lat: 29.789
  lon: 101.546
  altitude: 4412

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 贡嘎主峰
    lat: 29.58
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events:
      - sunrise
      - sunset
