id: transit_gaoersi_pass
name: 高尔寺山垭口
groups:
  - 318
location:
  lat: 30.039849
  lon: 101.345279
  altitude: 4412

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 贡嘎主峰
    lat: 29.596
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events:
      - sunrise
      - sunset
