id: yading_pearl_lake
name: 珍珠海
location:
  lat: 28.431
  lon: 100.288
  altitude: 4100

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 仙乃日
    lat: 28.9
    lon: 100.06
    altitude: 6032
    weight: primary
    applicable_events:
      - sunrise
      - sunset
