id: yading_luorong_pasture
name: 洛绒牛场
location:
  lat: 28.442
  lon: 100.318
  altitude: 4180

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 央迈勇
    lat: 28.91
    lon: 100.14
    altitude: 5958
    weight: primary
    applicable_events:
      - sunrise
      - sunset
