id: yading_luorong_pasture
name: 洛绒牛场
location:
  lat: 28.389973
  lon: 100.381201
  altitude: 4180

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 央迈勇
    lat: 28.398
    lon: 100.334
    altitude: 5958
    weight: primary
    applicable_events:
      - sunrise
      - sunset
