id: yading_echushan_view
name: 俄初山观景台
groups:
  - yading
location:
  lat: 28.562789
  lon: 100.194275
  altitude: 3900

capabilities:
  - sunrise
  - sunset

targets:
  - name: 仙乃日
    lat: 28.433
    lon: 100.316
    altitude: 6032
    weight: primary
    applicable_events:
      - sunrise
      - sunset
