id: yading_pearl_lake
name: 珍珠海
groups:
  - yading
location:
  lat: 28.438425
  lon: 100.305771
  altitude: 4100

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 仙乃日
    lat: 28.433
    lon: 100.316
    altitude: 6032
    weight: primary
    applicable_events:
      - sunrise
      - sunset
