id: yading_five_color_lake
name: 五色海
location:
  lat: 28.380442
  lon: 100.351471
  altitude: 4700

capabilities:
  - sunrise
  - sunset

targets:
  - name: 夏诺多吉
    lat: 28.413
    lon: 100.371
    altitude: 5958
    weight: primary
    applicable_events:
      - sunrise
      - sunset
