id: yading_milk_lake
name: 牛奶海
location:
  lat: 28.374149
  lon: 100.345963
  altitude: 4600

capabilities:
  - sunrise
  - sunset

targets:
  - name: 央迈勇
    lat: 28.398
    lon: 100.334
    altitude: 5958
    weight: primary
    applicable_events:
      - sunrise
      - sunset
