id: yala_tagong_view
name: 塔公草原机位
groups:
  - yala
location:
  lat: 30.332783
  lon: 101.553397
  altitude: 3730

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunrise
      - sunset
