id: yala_gunong
name: 姑弄村
location:
  lat: 30.355645
  lon: 101.516433
  altitude: 3600

capabilities:
  - sunrise
  - sunset

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunrise
      - sunset
