id: yala_gedilamu
name: 格底拉姆
location:
  lat: 30.2359
  lon: 101.644077
  altitude: 4300

capabilities:
  - sunset
  - stargazing

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunset
