id: yala_yunrao_view
name: 云绕亚拉
location:
  lat: 30.38665
  lon: 101.661825
  altitude: 4000

capabilities:
  - sunrise
  - sunset
  - cloud_sea

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunrise
      - sunset
