id: yala_balangshengdu
name: 八郎生都
location:
  lat: 30.338197
  lon: 101.42751
  altitude: 4200

capabilities:
  - sunrise
  - sunset
  - stargazing

targets:
  - name: 亚拉神山
    lat: 30.380
    lon: 101.560
    altitude: 5820
    weight: primary
    applicable_events:
      - sunrise
      - sunset
