id: zhagushan_pass
name: 鹧鸪山垭口机位
location:
  lat: 31.853109
  lon: 102.672527
  altitude: 3780

capabilities:
  - sunrise
  - sunset
  - snow_tree

targets:
  - name: 鹧鸪山主峰
    lat: 31.792
    lon: 102.922
    altitude: 4450
    weight: primary
    applicable_events:
      - sunrise
      - sunset
