id: zheduo_gongga
name: 折多山
location:
  lat: 30.05
  lon: 101.72
  altitude: 4298

# 该观景台支持的景观类型
capabilities:
  - sunrise
  - sunset
  - stargazing
  - cloud_sea
  - frost
  - snow_tree
  - ice_icicle

targets:
  - name: 贡嘎主峰
    lat: 29.58
    lon: 101.88
    altitude: 7556
    weight: primary
    applicable_events: null
